#!/bin/bash

verilator --trace \
   --cc rtl/x_micro_sequencer.sv \
   --cc rtl/x_micro_sequencer_ram.sv \
   --exe verif/x_micro_sequencer_tb.cpp \
   +define+SIM

make -C obj_dir -f Vx_micro_sequencer.mk Vx_micro_sequencer

./obj_dir/Vx_micro_sequencer
