#!/bin/bash

verilator --trace \
   --cc rtl/x_micro_sequencer.sv \
   --exe verif/x_micro_sequencer_tb.cpp \

make -C obj_dir -f Vx_micro_sequencer.mk Vx_micro_sequencer

./obj_dir/Vx_micro_sequencer
