#!/bin/bash

verilator --trace \
   --cc rtl/x_dummy.sv \
   --cc ../../submodules/x_byte_des/rtl/x_byte_des.sv \
   --cc ../../submodules/x_micro_scope/rtl/x_micro_scope.sv \
   --cc ../../submodules/x_micro_scope/rtl/x_micro_scope_ram.sv \
   --cc ../../submodules/x_micro_sequencer/rtl/x_micro_sequencer.sv \
   --cc ../../submodules/x_micro_sequencer/rtl/x_micro_sequencer_ram.sv \
   --cc ../../submodules/x_uart_rx/rtl/x_uart_rx.sv \
   --cc ../../submodules/x_uart_tx/rtl/x_uart_tx.sv \
   --cc ../../submodules/x_mem/rtl/x_mem.sv \
   --exe verif/x_dummy_tb.cpp \
   +define+SIM

make -C obj_dir -f Vx_dummy.mk Vx_dummy

./obj_dir/Vx_dummy
