#!/bin/bash
echo "========================================================"
echo "Running synth..."
rm -f syn.log
yosys -p 'synth_ice40 -top x_dummy -blif a.blif -json a.json'\
   rtl/x_dummy.sv \
   ../../submodules/x_byte_des/rtl/x_byte_des.sv \
   ../../submodules/x_micro_scope/rtl/x_micro_scope.sv \
   ../../submodules/x_micro_scope/rtl/x_micro_scope_ram.sv \
   ../../submodules/x_micro_sequencer/rtl/x_micro_sequencer.sv \
   ../../submodules/x_micro_sequencer/rtl/x_micro_sequencer_ram.sv \
   ../../submodules/x_uart_rx/rtl/x_uart_rx.sv \
   ../../submodules/x_uart_tx/rtl/x_uart_tx.sv \
   ../../submodules/x_mem/rtl/x_mem.sv \
   > syn.log
cat syn.log | grep -A30 statistics
echo "========================================================"
echo "Running place and route..."
rm -f pnr.log
nextpnr-ice40 --hx8k --json a.json --package ct256 --pcf etc/x_dummy.pcf --asc a.asc &> pnr.log
cat pnr.log | grep -A6 "Device utilisation"
echo "========================================================"
echo "Running Timing check..."
icetime -d hx8k a.asc > a.time
cat a.time
