#!/bin/bash

verilator --trace \
   --cc rtl/x_delay_line.sv \
   --cc rtl/x_delay_line_cell.sv \
   --exe tb/x_delay_line_tb.cpp \
   +define+SIM

make -C obj_dir -f Vx_delay_line.mk Vx_delay_line

./obj_dir/Vx_delay_line
