#!/bin/bash

verilator --trace \
   --cc rtl/x_micro_scope.sv \
   --cc rtl/x_micro_scope_ram.sv \
   --exe verif/x_micro_scope_tb.cpp \
   +define+SIM

make -C obj_dir -f Vx_micro_scope.mk Vx_micro_scope

./obj_dir/Vx_micro_scope
